In [19]:
from numpy import array, diag, zeros
from numpy.linalg import eig, inv

In [2]:
A = array([
    [1,2],
    [3,4],
])

In [3]:
eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [4]:
A = array([
    [ 2.5, -0.5],
    [ 1.5,  0.5]
])
eig(A)

(array([2., 1.]),
 array([[0.70710678, 0.31622777],
        [0.70710678, 0.9486833 ]]))

In [5]:
v = array([[1,2], [3,2]])
inv_v = inv(v)

In [6]:
s = array([1,2])
d = diag(s)

In [7]:
inv_v

array([[-0.5 ,  0.5 ],
       [ 0.75, -0.25]])

In [8]:
d

array([[1, 0],
       [0, 2]])

In [9]:
v.dot(d).dot(inv_v)

array([[ 2.5, -0.5],
       [ 1.5,  0.5]])

## Get the eigenvalues and eigenvectors

In [21]:
A = array([[1,2],[3,4]])  # 2x2 matrix

values, vectors = eig(A)

In [22]:
values

array([-0.37228132,  5.37228132])

In [23]:
vectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [28]:
zeros(values.size)

array([0., 0.])

In [14]:
vectors[:, 0]

array([-0.82456484,  0.56576746])

In [43]:
# Confirm the first eigenvector
A.dot(vectors[:, 0])

array([ 0.30697009, -0.21062466])

In [44]:
vectors[:, 0] * values[0]

array([ 0.30697009, -0.21062466])

In [38]:
A.dot(vectors[:, 0]) == (vectors[:, 0] * values[0])

array([ True, False])

In [45]:
# Confirm the second eigenvector
A.dot(vectors[:, 1])

array([-2.23472698, -4.88542751])

In [46]:
vectors[:, 1] * values[1]

array([-2.23472698, -4.88542751])

In [28]:
## Reconstruct the matrix from the eigenvectors

In [33]:
from numpy import diag
from numpy.linalg import inv

In [34]:
A

array([[1, 2],
       [3, 4]])

In [35]:
values, vectors = eig(A)

In [38]:
vector_invs = inv(vectors)
values_diag = diag(values)

In [39]:
vectors.dot(values_diag).dot(vector_invs)

array([[1., 2.],
       [3., 4.]])