# Matrices and Matrix Operations

This notebook goes through the various types of matrices and operations that can be performed on them. First, we demonstrate arithmetic operations on matrices to relate them to the familiar scalar operations, then perform matrix-to-vector and matrix-to-scalar operations.
Next, we go through some of the common types of matrices, like triangular and orthogonal matrices.
The last part of the tutorial is an overview of matrix operations, like Inverse, Transpose, and Determinant. All samples are implemented using Numpy.

The final output "project" of this tutorial is a simple Python implementation of the Laplace Expansion to compute for the determinant of a matrix.

---

We can think of a matrix as a two-dimensional array of rows and columns. Numpy allow us to create a matrix through its `array` module.

In [1]:
from numpy import array

## Matrix Arithmetic

We can perform arithmetic operations on matrices with the same dimensions. The operation is performed element-wise between the matrices.

In math notation, a matrix is represented by a capital letter, like $A$. Each element of $A$ is represented by the small letter equivalent of the matrix variable, and its position in the matrix is indicated by a subscript.
For example, $a_{1,1}$ is the element on the first row and first column of matrix $A$.

### Matrix Addition

Adding two matrices of the same dimensions produces a new matrix with the same dimension.

Notation: $C = A + B$

$
C =
\begin{pmatrix}
a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2} & a_{1,3} + b_{1,3} \\
a_{2,1} + b_{2,1} & a_{2,2} + b_{2,2} & a_{2,3} + b_{2,3}
\end{pmatrix}
$

In [2]:
A = array([[1,2,3], [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
B = array([[1,3,5], [2,4,6]])
print(B)

[[1 3 5]
 [2 4 6]]


In [4]:
C = A + B
print(C)

[[ 2  5  8]
 [ 6  9 12]]


### Matrix Subtraction

In [5]:
C = A - B
print(C)

[[ 0 -1 -2]
 [ 2  1  0]]


### Matrix Division

In [6]:
C = A / B
print(C)

[[1.         0.66666667 0.6       ]
 [2.         1.25       1.        ]]


### Matrix Multiplication (Hadamard Product)

The Hadamard Product is the element-wise product of two matrices.

Notation: $C = A \circ B$

$
C =
\begin{pmatrix}
a_{1,1} \times b_{1,1} & a_{1,2} \times b_{1,2} & a_{1,3} \times b_{1,3} \\
a_{2,1} \times b_{2,1} & a_{2,2} \times b_{2,2} & a_{2,3} \times b_{2,3}
\end{pmatrix}
$

In [7]:
A = array([[1,2,3], [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [8]:
B = array([[1,3,5], [2,4,6]])
print(B)

[[1 3 5]
 [2 4 6]]


In [9]:
C = A * B
print(C)

[[ 1  6 15]
 [ 8 20 36]]


### Matrix Dot Product (Matrix-Matrix Multiplication)

The Dot Product involves multiplying two matrices that are not necessarily the same dimensions, but should abide by the following rule: The number of columns of the first matrix must be equal to the number of rows in the second matrix, such that each row in the first matrix is multiplied by each column in the second matrix.

Notation: $C = A \cdot B$

\begin{equation*}
A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3}
\end{pmatrix}
\end{equation*}

\begin{equation*}
B = 
\begin{pmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2} \\
b_{3,1} & b_{3,2} \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
C =
\begin{pmatrix}
a_{1,1} \times b_{1,1} + a_{1,2} \times b_{2,1} + a_{1,3} \times b_{3,1} && a_{1,1} \times b_{1,2} + a_{1,2} \times b_{2,2} + a_{1,3} \times b_{3,2} \\
a_{2,1} \times b_{1,1} + a_{2,2} \times b_{2,1} + a_{2,3} \times b_{3,1} && a_{2,1} \times b_{1,2} + a_{2,2} \times b_{2,2} + a_{2,3} \times b_{3,2}
\end{pmatrix}
\end{equation*}



In [19]:
A = array([[1,1,1], [2,2,2]])
print(A)

[[1 1 1]
 [2 2 2]]


In [20]:
B = array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
C = A.dot(B)
print(C)

[[ 9 12]
 [18 24]]


In [10]:
# From Python 3.5 and later
A @ B

array([[ 6, 14],
       [ 6, 10]])

### Matrix-Vector Multiplication

**Rule**: The number of columns in the matrix should be equal to the number of items in the vector

Notation: $C = A \cdot v$

\begin{equation*}
A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3}
\end{pmatrix}
\end{equation*}

\begin{equation*}
v = 
\begin{pmatrix}
v_1 \\
v_2 \\
v_3 \\
\end{pmatrix}
\end{equation*}

\begin{equation*}
C = 
\begin{pmatrix}
(a_{1,1} \times v_1) + (a_{1,2} \times v_2) + (a_{1,3} \times v_3) && (a_{2,1} \times v_1) + (a_{2,2} \times v_2) + (a_{2,3} \times v_3) \\
\end{pmatrix}
\end{equation*}

In [3]:
A = array([[1,2,3], [2,3,4]])
print(A)

[[1 2 3]
 [2 3 4]]


In [4]:
v = array([0.75,0.25,0.5])
print(v)

[0.75 0.25 0.5 ]


In [5]:
C = A.dot(v)
print(C)

[2.75 4.25]


In [11]:
print(A,v,C, sep='\n\n')

[[1 2 3]
 [2 3 4]]

[0.75 0.25 0.5 ]

[2.75 4.25]


---

## Types of Matrices

### Square Matrix

The number of rows is equal to the number of columns

In [17]:
square = array([[1,2,3], [1,2,3], [1,2,3]])
print(square)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Symmetric Matrix

The top right triangle is equal to the bottom left triangle

In [18]:
symmetric = array([[1,2,3], [2,1,2], [3,2,1]])
print(symmetric)

[[1 2 3]
 [2 1 2]
 [3 2 1]]


### Triangular Matrix

Values are either at the top right triangle or lower left triange with respect to the main diagonal

In [19]:
upper_triangular = array([[1,2,3], [0,2,3], [0,0,3]])
print(upper_triangular)

[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [20]:
lower_triangular = array([[1,0,0], [1,2,0], [1,2,3]])
print(lower_triangular)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


You can generate an upper triangular or lower triangular matrix with numpy

In [21]:
from numpy import triu
from numpy import tril

In [22]:
A = array([[1,2,3], [1,2,3], [1,2,3]])
print(A)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
triu(A)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [24]:
tril(A)

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

### Diagonal Matrix

Values outside of the main diagonal are zero, essentially making the matrix a vector of the values in the diagonal

A diagonal matrix can be generated in numpy

In [25]:
from numpy import diag

In [26]:
M = array([[1,2,3], [1,2,3], [1,2,3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
# Create a vector from the main diagonal
d = diag(M)
print(d)

[1 2 3]


In [28]:
# Create a diagonal matrix from the diagonal vector 
diag(d)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Identity Matrix

An identity matrix is a matrix that does not change a vector when that vector is multiplied by the matrix

In simple terms, the identity matrix is a vector of the main diagonal values, where all the values are 1

In [29]:
from numpy import identity

In [30]:
identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Orthogonal Matrix

A matrix is orthogonal if its dot product with its transpose results to the identity matrix

All orthogonal matrices are square matrices.

The inverse of an orthogonal matrix is equal to its transpose.

In [31]:
Q = array([[1, 0], [0, -1]])
print(Q)

[[ 1  0]
 [ 0 -1]]


In [32]:
V = Q.T
print(V)

[[ 1  0]
 [ 0 -1]]


In [33]:
Q.dot(V)

array([[1, 0],
       [0, 1]])

# Matrix Operations

## Transpose

Flipping the dimensions of a matrix

Notation:  $A^T$

\begin{equation*}
A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3}
\end{pmatrix}
\end{equation*}

\begin{equation*}
A^T = 
\begin{pmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{pmatrix}
\end{equation*}

In [34]:
A = array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [35]:
print(A.T)

[[1 3]
 [2 4]
 [3 5]]


## Inverse

Inversion means finding a matrix that, when multiplied by the original matrix, results to the identity matrix.

A non-invertible matrix is called a singular.

Notation:  $A^{-1}$

\begin{equation*}
A^{-1} \cdot A = I
\end{equation*}

In [36]:
from numpy.linalg import inv

In [37]:
A = array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [38]:
I = inv(A)
print(I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [39]:
M = A.dot(I)
print(M)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## Trace

A trace is the sum of the values in the main diagonal of a square matrix

Notation:  $tr(A)$

\begin{equation*}
A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3}
\end{pmatrix}
\end{equation*}

\begin{equation*}
tr(A) = a_{1,1} + a_{2,2} + a_{3,3} \\
\end{equation*}

In [40]:
from numpy import trace

In [41]:
A = array([[1,2,3], [3,4,5], [6,7,8]])
print(A)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [42]:
B = trace(A)
print(B)

13


## Determinant

The determinant is the scalar representation of the volume of the matrix. It is the product of all the eigenvalues of the matrix. In other words, it describes the way the matrix will scale another matrix when they are multiplied together.

A zero determinant means that the matrix is not invertible.

In [43]:
from numpy.linalg import det

In [44]:
A = array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
d = det(A)
print(d)

-9.51619735392994e-16


## Rank

The rank is the number of linearly independent rows and columns in a matrix

In [46]:
from numpy.linalg import matrix_rank

In [47]:
A = array([[1,2,3], [2,4,6]])
matrix_rank(A)

1

In [48]:
B = array([[1,2], [3,4]])
matrix_rank(B)

2

In [49]:
C = array([[0,0,0]])
matrix_rank(C)

0

## Calculate the Determinant

The following code follows the Laplace Expansion, wherein to compute for the determinant of an nxn matrix, we first compute for the determinants of its sub-matrices. The determinant of a sub-matrix is called a _minor_.

In [3]:
import copy
import numpy as np

def get_determinant(matrix):
    if matrix.shape[0] == 1:
        return matrix.shape[0]
    elif matrix.shape[0] == 2:
        return (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])
    else:
        determinant = 0
        
        for col in range(matrix.shape[1]):
            new_matrix = copy.deepcopy(matrix)
            new_matrix = np.delete(new_matrix, 0, 0)     # remove the first row (axis=0)
            print('m1\n', matrix, '\nnm1\n', new_matrix)
            new_matrix = np.delete(new_matrix, col, 1)   # remove the col-th column (axis=1)
            print('m2\n', matrix, '\nnm2\n', new_matrix)


#             print(matrix[0][col], '\n' , new_matrix)
            cofactor = ((-1)**col)
            print('col: ', col, ' , cofactor: ', cofactor)
            
            determinant += cofactor * matrix[0][col] * get_determinant(new_matrix)
            
        return determinant

In [115]:
(-1)**0

1

In [116]:
Z = array([[2,3]])
get_determinant(Z)

1

In [117]:
B = array([[1,2],[3,4]])
print(B)
get_determinant(B)

[[1 2]
 [3 4]]


-2

In [118]:
C = array([[1,2,3], [4,5,6], [7,8,9]])
print(C)
get_determinant(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
m1
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm1
 [[4 5 6]
 [7 8 9]]
m2
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm2
 [[5 6]
 [8 9]]
col:  0  , cofactor:  1
m1
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm1
 [[4 5 6]
 [7 8 9]]
m2
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm2
 [[4 6]
 [7 9]]
col:  1  , cofactor:  -1
m1
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm1
 [[4 5 6]
 [7 8 9]]
m2
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
nm2
 [[4 5]
 [7 8]]
col:  2  , cofactor:  1


0

In [119]:
D = array([[1,2,3,4],[4,3,5,6],[8,4,2,1],[3,2,4,1]])
print(D)
get_determinant(D)

[[1 2 3 4]
 [4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]]
m1
 [[1 2 3 4]
 [4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]] 
nm1
 [[4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]]
m2
 [[1 2 3 4]
 [4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]] 
nm2
 [[3 5 6]
 [4 2 1]
 [2 4 1]]
col:  0  , cofactor:  1
m1
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm1
 [[4 2 1]
 [2 4 1]]
m2
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm2
 [[2 1]
 [4 1]]
col:  0  , cofactor:  1
m1
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm1
 [[4 2 1]
 [2 4 1]]
m2
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm2
 [[4 1]
 [2 1]]
col:  1  , cofactor:  -1
m1
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm1
 [[4 2 1]
 [2 4 1]]
m2
 [[3 5 6]
 [4 2 1]
 [2 4 1]] 
nm2
 [[4 2]
 [2 4]]
col:  2  , cofactor:  1
m1
 [[1 2 3 4]
 [4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]] 
nm1
 [[4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]]
m2
 [[1 2 3 4]
 [4 3 5 6]
 [8 4 2 1]
 [3 2 4 1]] 
nm2
 [[4 5 6]
 [8 2 1]
 [3 4 1]]
col:  1  , cofactor:  -1
m1
 [[4 5 6]
 [8 2 1]
 [3 4 1]] 
nm1
 [[8 2 1]
 [3 4 1]]
m2
 [[4 5 6]
 [8 2 1]
 [3 4 1]] 
nm2
 [[2 1]
 [4 1]]
col:  0  , cofactor:  1
m1
 [[4 5 6]
 [8 2 1]
 [3

-99

In [54]:
E = array([[1,3,5,7,9],[4,6,3,7,5],[5,10,8,3,1],[1,5,3,7,6],[8,1,7,5,8]])
print(E)
get_determinant(E)


[[ 1  3  5  7  9]
 [ 4  6  3  7  5]
 [ 5 10  8  3  1]
 [ 1  5  3  7  6]
 [ 8  1  7  5  8]]
1 
 [[ 6  3  7  5]
 [10  8  3  1]
 [ 5  3  7  6]
 [ 1  7  5  8]]
6 
 [[8 3 1]
 [3 7 6]
 [7 5 8]]
8 
 [[7 6]
 [5 8]]
3 
 [[3 6]
 [7 8]]
1 
 [[3 7]
 [7 5]]
3 
 [[10  3  1]
 [ 5  7  6]
 [ 1  5  8]]
10 
 [[7 6]
 [5 8]]
3 
 [[5 6]
 [1 8]]
1 
 [[5 7]
 [1 5]]
7 
 [[10  8  1]
 [ 5  3  6]
 [ 1  7  8]]
10 
 [[3 6]
 [7 8]]
8 
 [[5 6]
 [1 8]]
1 
 [[5 3]
 [1 7]]
5 
 [[10  8  3]
 [ 5  3  7]
 [ 1  7  5]]
10 
 [[3 7]
 [7 5]]
8 
 [[5 7]
 [1 5]]
3 
 [[5 3]
 [1 7]]
3 
 [[4 3 7 5]
 [5 8 3 1]
 [1 3 7 6]
 [8 7 5 8]]
4 
 [[8 3 1]
 [3 7 6]
 [7 5 8]]
8 
 [[7 6]
 [5 8]]
3 
 [[3 6]
 [7 8]]
1 
 [[3 7]
 [7 5]]
3 
 [[5 3 1]
 [1 7 6]
 [8 5 8]]
5 
 [[7 6]
 [5 8]]
3 
 [[1 6]
 [8 8]]
1 
 [[1 7]
 [8 5]]
7 
 [[5 8 1]
 [1 3 6]
 [8 7 8]]
5 
 [[3 6]
 [7 8]]
8 
 [[1 6]
 [8 8]]
1 
 [[1 3]
 [8 7]]
5 
 [[5 8 3]
 [1 3 7]
 [8 7 5]]
5 
 [[3 7]
 [7 5]]
8 
 [[1 7]
 [8 5]]
3 
 [[1 3]
 [8 7]]
5 
 [[ 4  6  7  5]
 [ 5 10  3  1]
 [ 1  5  7  6]
 [ 8

-687

In [55]:
import copy
def new_matrix(a,i):#FUNCTION TO FIND THE NEW MATRIX
    arr = copy.deepcopy(a) 
    if len(arr) == 2:

        return arr
    else:
        arr.pop(0)
        print('arr: ', arr)
        for j in arr:
            j.pop(i)

        print('new_matrix: ', arr)
        return arr
    
def determinant(a):#FUNCTION TO FIND THE DETERMINANT OF A MATRIX
    if len(a) == 1:
        pro = a[0]
        return pro
    
    elif len(a) == 2:
            pro = a[0][0]*a[1][1] - a[1][0]*a[0][1]
            return pro

    else:
        pro = 0
        for i in range(len(a[0])):
            pro += ((-1)**i)*a[0][i]*determinant(new_matrix(a,i))    
        return pro         

In [56]:
A = [2]
determinant(A)

2

In [57]:
B = [[1,2],[3,4]]
determinant(B)

-2

In [58]:
C = [[1,2,3],[4,5,6], [7,8,9]]
determinant(C)

arr:  [[4, 5, 6], [7, 8, 9]]
new_matrix:  [[5, 6], [8, 9]]
arr:  [[4, 5, 6], [7, 8, 9]]
new_matrix:  [[4, 6], [7, 9]]
arr:  [[4, 5, 6], [7, 8, 9]]
new_matrix:  [[4, 5], [7, 8]]


0